apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: lesson1-4
  labels:
    app: gowebb
spec:
  containers:
    - name: web
      image: darktulip/lesson1:v0.2

      ports: 
        - name: web
          containerPort: 8080
          protocol: TCP

       
