apiVersion: v1
kind: Namespace
metadata:
  name: lesson1-5

--- # "---"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: lesson1-5
  labels:
    app: goapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata: 
      labels:
        app: goapp
    spec:
      containers:
      - name: web
        image: darktulip/lesson1:v0.2
        ports: 
        - containerPort: 8080
